/*
* @Author: Administrator
* @Date:   2016-10-14 11:08:44
* @Last Modified by:   Administrator
* @Last Modified time: 2016-10-17 13:49:59
*/

var gPage=`
<div class="bannar" style="margin-bottom:0;">
    <div class="yxtopkuang">
  <ul class="yxtop_ul">
    <li style="">
      <a href="#tabbar-game-detail" class="mui-tab-item"><img src="http://img-home.49app.com./Uploads/2015-11/56459840b9192.jpg" alt=""></a>
      </li><li style="margin-right:0;">
      <a href="#tabbar-game-detail" class="mui-tab-item"><img src="http://img-home.49app.com./Uploads/2016-04/57104488a293c.jpg" alt=""></a>
      </li> </ul>
</div>    </div>

<div class="mui-input-row mui-search">
  <input type="search" class="mui-input-clear" placeholder="">
</div>

<ul class="youxi_ul" id="youxi_content">
  <li><div class="youxiicon fl"><a href="#tabbar-game-detail" class="mui-tab-item"><img src="images/baye.jpg"></a></div><div class="youxikuang_r fr"><div class="youxiinfo_div fl"><p class="youxiname"><a href="#tabbar-game-detail" class="mui-tab-item">霸业</a></p><p class="youxiinfo_p">版本：</p><p class="youxiinfo_p2">大小：90M <img src="http://img-home.49app.com/images/xing_blue.png"><img src="http://img-home.49app.com/images/xing_blue.png"><img src="http://img-home.49app.com/images/xing_blue.png"><img src="http://img-home.49app.com/images/xing_blue.png"><img src="http://img-home.49app.com/images/xing_blue.png"></p></div><a href="game.apk" download="game1.apk" class="youxidl_a db fr"><img src="http://img-home.49app.com/wap/platfor/images/xz_a01.png"></a></div></li>

 <li><div class="youxiicon fl"><a href="#tabbar-game-detail" class="mui-tab-item"><img src="images/fentian.png"></a></div><div class="youxikuang_r fr"><div class="youxiinfo_div fl"><p class="youxiname"><a href="#tabbar-game-detail" class="mui-tab-item">焚天</a></p><p class="youxiinfo_p">版本：</p><p class="youxiinfo_p2">大小：88MM <img src="http://img-home.49app.com/images/xing_blue.png"><img src="http://img-home.49app.com/images/xing_blue.png"><img src="http://img-home.49app.com/images/xing_blue.png"><img src="http://img-home.49app.com/images/xing_blue.png"><img src="http://img-home.49app.com/images/xing_blue.png"></p></div><a href="game.apk" download="game2.apk" class="youxidl_a db fr"><img src="http://img-home.49app.com/wap/platfor/images/xz_a01.png"></a></div></li>
 <li><div class="youxiicon fl"><a href="#tabbar-game-detail" class="mui-tab-item"><img src="images/fbys.png"></a></div><div class="youxikuang_r fr"><div class="youxiinfo_div fl"><p class="youxiname"><a href="#tabbar-game-detail" class="mui-tab-item">风暴要塞</a></p><p class="youxiinfo_p">版本：0</p><p class="youxiinfo_p2">大小：M <img src="http://img-home.49app.com/images/xing_blue.png"><img src="http://img-home.49app.com/images/xing_blue.png"><img src="http://img-home.49app.com/images/xing_blue.png"><img src="http://img-home.49app.com/images/xing_blue.png"><img src="http://img-home.49app.com/images/xing_blue.png"><img src="http://img-home.49app.com/images/xing_blue.png"><img src="http://img-home.49app.com/images/xing_blue.png"><img src="http://img-home.49app.com/images/xing_blue.png"><img src="http://img-home.49app.com/images/xing_blue.png"><img src="http://img-home.49app.com/images/xing_blue.png"></p></div><a href="http://down.49app.com/down/zsjx/android/0.0/49you_b_myzj001.apk" download="game3.apk" class="youxidl_a db fr"><img src="http://img-home.49app.com/wap/platfor/images/xz_a01.png"></a></div></li>
 <li><div class="youxiicon fl"><a href="#tabbar-game-detail" class="mui-tab-item"><img src="images/wdqk.png"></a></div><div class="youxikuang_r fr"><div class="youxiinfo_div fl"><p class="youxiname"><a href="#tabbar-game-detail" class="mui-tab-item">武道乾坤</a></p><p class="youxiinfo_p">版本：0</p><p class="youxiinfo_p2">大小：64.72 M <img src="http://img-home.49app.com/images/xing_blue.png"><img src="http://img-home.49app.com/images/xing_blue.png"><img src="http://img-home.49app.com/images/xing_blue.png"><img src="http://img-home.49app.com/images/xing_blue.png"><img src="http://img-home.49app.com/images/xing_blue.png"></p></div><a href="http://down.49app.com/down/lsy/android/1.1/49you_b_lsy001.apk" download="game4.apk" class="youxidl_a db fr"><img src="http://img-home.49app.com/wap/platfor/images/xz_a01.png"></a></div></li>
 <li><div class="youxiicon fl"><a href="#tabbar-game-detail" class="mui-tab-item"><img src="images/yjmt.png"></a></div><div class="youxikuang_r fr"><div class="youxiinfo_div fl"><p class="youxiname"><a href="#tabbar-game-detail" class="mui-tab-item">一剑灭天</a></p><p class="youxiinfo_p">版本：</p><p class="youxiinfo_p2">大小：93MM <img src="http://img-home.49app.com/images/xing_blue.png"><img src="http://img-home.49app.com/images/xing_blue.png"><img src="http://img-home.49app.com/images/xing_blue.png"><img src="http://img-home.49app.com/images/xing_blue.png"><img src="http://img-home.49app.com/images/xing_blue.png"><img src="http://img-home.49app.com/images/xing_blue.png"><img src="http://img-home.49app.com/images/xing_blue.png"><img src="http://img-home.49app.com/images/xing_blue.png"><img src="http://img-home.49app.com/images/xing_blue.png"><img src="http://img-home.49app.com/images/xing_blue.png"></p></div><a href="http://down.49app.com/down/lf/android/0.0/49you_b_zmlf001.apk" download="game5.apk" class="youxidl_a db fr"><img src="http://img-home.49app.com/wap/platfor/images/xz_a01.png"></a></div></li>
 <li><div class="youxiicon fl"><a href="#tabbar-game-detail" class="mui-tab-item"><img src="http://img-home.49app.com./Uploads/2016-09/57e1f083a5a2a.png"></a></div><div class="youxikuang_r fr"><div class="youxiinfo_div fl"><p class="youxiname"><a href="#tabbar-game-detail" class="mui-tab-item">次元战争</a></p><p class="youxiinfo_p">版本：2.1</p><p class="youxiinfo_p2">大小：80MM <img src="http://img-home.49app.com/images/xing_blue.png"><img src="http://img-home.49app.com/images/xing_blue.png"><img src="http://img-home.49app.com/images/xing_blue.png"><img src="http://img-home.49app.com/images/xing_blue.png"><img src="http://img-home.49app.com/images/xing_blue.png"></p></div><a href="http://down.49app.com/down/(53)/android/0.0/49you_b_cyzz001.apk" download="game6.apk" class="youxidl_a db fr"><img src="http://img-home.49app.com/wap/platfor/images/xz_a01.png"></a></div></li>
 <li><div class="youxiicon fl"><a href="#tabbar-game-detail" class="mui-tab-item"><img src="http://img-home.49app.com./Uploads/2016-08/57b3da80687c4.png"></a></div><div class="youxikuang_r fr"><div class="youxiinfo_div fl"><p class="youxiname"><a href="#tabbar-game-detail" class="mui-tab-item">御天邪神</a></p><p class="youxiinfo_p">版本：0.0</p><p class="youxiinfo_p2">大小：69M <img src="http://img-home.49app.com/images/xing_blue.png"><img src="http://img-home.49app.com/images/xing_blue.png"><img src="http://img-home.49app.com/images/xing_blue.png"><img src="http://img-home.49app.com/images/xing_blue.png"><img src="http://img-home.49app.com/images/xing_blue.png"></p></div><a href="http://down.49app.com/down/ytxs/android/1.0/49you_b_ytxs001.apk" download="game7.apk" class="youxidl_a db fr"><img src="http://img-home.49app.com/wap/platfor/images/xz_a01.png"></a></div></li>
</ul>


`;
